# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
      #
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
       - uses: actions/checkout@v6
       - name: Install uv
         uses: astral-sh/setup-uv@v7
         with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: 0.9.27
       
       - name: Change Package Version
         run: |
          # Extract the tag name and remove the leading 'v'
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "Tag name: $TAG_NAME"

          # Update the version in pyproject.toml
          sed -i "s/\"0.0.0-dev\"/\"$TAG_NAME\"/" pyproject.toml

          # Print the updated pyproject.toml file
          cat pyproject.toml

            
       - name: Install build dependencies
         run: uv sync --all-extras
      
       - name: Build the project
         run: uv build

       - name: Publish to PyPI
         run: uv publish